### ISSUE TITLE
Problem with sing-box on merlin-wrt

### ISSUE THREAD

**Issue by Andrewprvrzv** [Dr4tez/sing-box4asus#1]
After install script, run sbs-setup and change config, start sbs, bit its fail with error that can't download files from resources (github and etc.). Any idea? Maybe Ithere is missing some pkg on entware? Could you show the list of your installed entware packages

**Comment by Dr4tez** [comment]
I didn't install any entware packages. The flash drive with entware is used here simply as a place for the sing-box binary file and the files it creates.
Have you tried this config.json in sing-box on other platforms? You can show it here, after replacing sensitive data with X's, as it is done in my config.json template.

**Comment by Andrewprvrzv** [comment]
```yaml
{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "dns-direct",
        "address": "XX.XX.XX.XX",
        "strategy": "prefer_ipv4",
        "detour": "direct"
      },
      {
        "tag": "dns-block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "query_type": [
          "NIMLOC",
          "SRV"
        ],
        "server": "dns-block"
      },
      {
        "domain_suffix": ".lan",
        "server": "dns-block"
      }
    ],
    "final": "dns-direct",
    "strategy": "prefer_ipv4",
    "independent_cache": true
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "mtu": 9000,
      "inet4_address": "172.19.0.1/28",
      "auto_route": true,
      "endpoint_independent_nat": true,
      "stack": "system",
      "sniff": true,
      "sniff_override_destination": true
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy",
      "server": "XXXXXXXXXXXXXXXX",
      "server_port": 443,
      "uuid": "XXXXXXXXXXXX",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "server_name": "XXXXXXXX",
        "utls": {
          "enabled": true,
          "fingerprint": "XXXXXXX"
        },
        "reality": {
          "enabled": true,
          "public_key": "XXXXXXXXXXXXX",
          "short_id": "XXXXX"
        }
      },
      "packet_encoding": ""
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "direct",
      "tag": "bypass"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "network": "udp",
        "port": [
          135,
          137,
          138,
          139,
          5353
        ],
        "outbound": "block"
      },
      {
        "rule_set": [
          "geoip-ru",
          "geoip-by",
          "geosite-yandex",
          "geosite-telegram",
          "geosite-whatsapp",
          "geosite-github",
          "geosite-tiktok"
        ],
        "outbound": "direct"
      },
      {
        "rule_set": [
          "geosite-youtube",
          "geosite-intel",
          "geosite-intel-dev"
        ],
        "outbound": "proxy"
      },
      {
        "ip_is_private": true,
        "outbound": "direct"
      },
      {
        "domain_suffix": [
          ".ru",
          "blizzard.com",
          "battle.net",
          "like.video",
          ".xn--d1acj3b",
          ".xn--80adxhks",
          ".xn--80asehdb",
          ".xn--c1avg",
          ".xn--p1acf",
          ".xn--p1ai",
          ".xn--80aswg"
        ],
        "domain_keyword": [
          "steam",
          "google",
          "steampowered"
        ],
        "ip_cidr": [
          "91.108.56.0/22",
          "91.108.4.0/22",
          "91.108.8.0/22",
          "91.108.16.0/22",
          "91.108.12.0/22",
          "149.154.160.0/20",
          "91.105.192.0/23",
          "91.108.20.0/22",
          "185.76.151.0/24",
          "2001:b28:f23d::/48",
          "2001:b28:f23f::/48",
          "2001:67c:4e8::/48",
          "2001:b28:f23c::/48",
          "2a0a:f280::/32"
        ],
        "outbound": "direct"
      },
      {
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block"
      },
      {
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block"
      }
    ],
    "rule_set": [
      {
        "type": "remote",
        "tag": "geoip-ru",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geoip/geoip-ru.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geoip-by",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geoip/geoip-by.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-youtube",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-youtube.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-intel-dev",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-intel-dev.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-intel",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-intel.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-yandex",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-yandex.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-telegram",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-telegram.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-whatsapp",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-whatsapp.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-github",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-github.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-tiktok",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tiktok.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      }
    ],
    "final": "proxy",
    "auto_detect_interface": true
  },
  "experimental": {
    "cache_file": {
      "enabled": true
    },
    "clash_api": {
      "external_controller": "0.0.0.0:19090",
      "external_ui": "/opt/root/sing-box/ui",
      "secret": "XXXX"
    }
  }
}
```
This is my config, its work perfect on debian/ubuntu. But with your script on my AX86U with latest werlin-wrt I have an error:
`ERROR clash-api: download external ui error: Get "https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip": exchange4: context canceled | exchange6: context canceled`
Same error with github links.

Update: delete "dns" block of config and it's start!

But now have new problem. Execute on router `curl --interface tun0 ipinfo.io` return `Failed to connect to ipinfo.io port 80 after 15149 ms: Couldn't connect to server`. From local machines same result. No error in sing-box.
Router is the default gateway in network (DHCP). Any idea?

**Comment by Dr4tez** [comment]
First, remove the line `"auto_route": true,` from the config,
the router will not allow such impudence)
The script itself configures the necessary routes and iptables rules.

**Comment by Andrewprvrzv** [comment]
Давай по русски) Не помогло.
Текущий конфиг
```yaml
{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "mtu": 9000,
      "inet4_address": "172.19.0.1/28",
      "endpoint_independent_nat": true,
      "stack": "mixed",
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy",
      "server": "XXXXXXXXXXXXX",
      "server_port": 443,
      "uuid": "XXXXXXXXXXX",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "server_name": "XXXXXXX",
        "utls": {
          "enabled": true,
          "fingerprint": "XXXXXX"
        },
        "reality": {
          "enabled": true,
          "public_key": "XXXXXXXXXXXX",
          "short_id": "XXXX"
        }
      },
      "packet_encoding": ""
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "direct",
      "tag": "bypass"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "rule_set": [
          "geoip-ru",
          "geoip-by",
          "geosite-yandex",
          "geosite-telegram",
          "geosite-whatsapp",
          "geosite-github",
          "geosite-tiktok"
        ],
        "outbound": "direct"
      },
      {
        "rule_set": [
          "geosite-youtube",
          "geosite-intel",
          "geosite-intel-dev"
        ],
        "outbound": "proxy"
      },
      {
        "ip_is_private": true,
        "outbound": "direct"
      },
      {
        "domain_suffix": [
          ".ru",
          "blizzard.com",
          "battle.net",
          "like.video",
          ".xn--d1acj3b",
          ".xn--80adxhks",
          ".xn--80asehdb",
          ".xn--c1avg",
          ".xn--p1acf",
          ".xn--p1ai",
          ".xn--80aswg"
        ],
        "domain_keyword": [
          "steam",
          "google",
          "steampowered"
        ],
        "ip_cidr": [
          "91.108.56.0/22",
          "91.108.4.0/22",
          "91.108.8.0/22",
          "91.108.16.0/22",
          "91.108.12.0/22",
          "149.154.160.0/20",
          "91.105.192.0/23",
          "91.108.20.0/22",
          "185.76.151.0/24",
          "2001:b28:f23d::/48",
          "2001:b28:f23f::/48",
          "2001:67c:4e8::/48",
          "2001:b28:f23c::/48",
          "2a0a:f280::/32"
        ],
        "outbound": "direct"
      }
    ],
    "rule_set": [
      {
        "type": "remote",
        "tag": "geoip-ru",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geoip/geoip-ru.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geoip-by",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geoip/geoip-by.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-youtube",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-youtube.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-intel-dev",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-intel-dev.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-intel",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-intel.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-yandex",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-yandex.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-telegram",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-telegram.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-whatsapp",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-whatsapp.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-github",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-github.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      },
      {
        "type": "remote",
        "tag": "geosite-tiktok",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tiktok.srs",
        "download_detour": "direct",
        "update_interval": "24h0m0s"
      }
    ],
    "final": "proxy",
    "auto_detect_interface": true
  },
  "experimental": {
    "cache_file": {
      "enabled": true
    },
    "clash_api": {
      "external_controller": "0.0.0.0:19090",
      "external_ui": "/opt/root/sing-box/ui",
      "secret": "XXXX"
    }
  }
}
```
Dashboard Clash работает, sing-box тоже, но почему-то не редиректятся запросы
